### ISSUE TITLE
Global ToDo List

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#59]
### MIDI 
(see [Juce ReceiveMIDI](https://github.com/gbevin/ReceiveMIDI/blob/master/Source/Main.cpp))
- [x] In
  - [x] SysEx (?)
  - [x] MidiByte (?)
  - [x] SysRealTime (?)
- [x] Out
  - [x] MidiByte (?)
- [x] Improve MIDI out time precision (I guess it would be better to let the user change the block size to 64)
### Channels
- [ ] Names
- [ ] Standard configurations
### Externals
- [ ] Manage external libraries
### Reload
- [x] Automatic reload of the patch when it has been changed ?
I guess this is no more possible
### Preset
- [x] Ask the patch for other informations
### GUI
- [x] Add labels
- [x] Add Graphical Array Support
- [ ] VU-meter
### Console
- [x] Improve rendering (selectable, line break)
- [x] Manage sys_debuglevel = 1 && sys_verbose = 1;
### DSP
- [x] Optimize using process Raw

**Comment by pierreguillot** [comment]
*sys_debuglevel* is not necessary and *sys_verbose* should be implemented by libpd (PR is merging)
