### ISSUE TITLE
v0.1.0 - todo list

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#64]
- [x] MiniMock gain (481ec7c)
- [x] Install the DejaVu sans Serif (14cecac)
- [x] Console only behind the patch (no ideal solution I guess)
- [x] Move the text README (2b14893)
- [x] Reduce the release size (37a7d9a & ede6b6e)
- [x] Fix multi instance support for array and text (d7e0dd6)
- [x] Improve Plugins generation
- [x] AU not working properly (ae17475)
- [x] Linking problem of libpd on Windows (dll instead of lib)
- [x] Instrument version on Windows (7460d2b)
- [x] 32bits support for Windows
- [x] Change Linux package's name to CamomileLinux64 (551185)
- [x] Improve generation (make it usable from everywhere, specifying a folder)
- [x] Fx or Instrument could perhaps (in fact) be in the text file  
- [x] Change font size for Pd-0.48.1
- [x] Add information about what Bulgroz and Castafiore do
- [x] Add GUI colors
- [x] Improve plugin localization (Ableton Windows)
- [x] Check font size (does not seems totally equivalent with Pd)
- [x] Use extern image for background if available
- [x] Atom number
- [x] Atom symbol
